export let CONFIG = {
  C1: 1.0,
  C2: 2.0,
  C3: 4.0,
  COMPABILITY_THRESHOLD: 3.0,
  PERCENTAGE_NEW_NODE: 0.03,
  PERCENTAGE_NEW_CONNECTION: 0.05,
  PERCENTAGE_MUTATION: 0.8,
  PERCENTAGE_MUTATION_ADJUST_WEIGHT: 0.9,
  STAGNATION_THRESHOLD: 0.05,
  ADJUST_WEIGHT_FACTOR: 0.2,
  NEW_WEIGHT_RANGE: 1.0,
  ALLOW_LOOPS: false
};
